// Generated by scripts/make_report_eegnet_defaults.py.
#table(columns: (1fr, 1.2fr, 1fr, 1fr, 1fr),
  table.header([*Laboratory category*], [*Source balanced accuracy*], [*Hit labels*], [*Enemy-crash labels*], [*Wall-crash labels*]),
  [Rare], [80.7%], [26.2%], [34.8%], [27.1%],
  [Standard], [75.6%], [31.4%], [28.9%], [26.0%],
  [Win], [74.7%], [35.1%], [41.7%], [31.1%],
  [Loss], [74.2%], [24.9%], [21.5%], [22.4%],
)
