// Generated by scripts/make_report_eegnet_defaults.py.
#table(columns: (.65fr, 1.15fr, .8fr, .9fr, 1fr, 1fr),
  table.header([*Label*], [*Game event*], [*N*], [*Event labels*], [*Gameplay controls*], [*Difference (pp)*]),
  [Rare], [Missile hit], [17], [28.7%], [18.2%], [+10.5],
  [Rare], [Enemy crash], [17], [42.1%], [18.2%], [+23.9],
  [Rare], [Wall crash], [16], [31.5%], [17.9%], [+13.6],
  [Win], [Missile hit], [14], [65.5%], [51.6%], [+13.8],
  [Win], [Enemy crash], [14], [70.7%], [51.6%], [+19.0],
  [Win], [Wall crash], [13], [61.0%], [51.8%], [+9.1],
)
