// Generated by analysis/results.py.
#table(columns: (.65fr, 1.15fr, .8fr, .9fr, 1fr, 1fr),
  table.header([*Label*], [*Game event*], [*N*], [*Event labels*], [*Gameplay controls*], [*Difference (pp)*]),
  [Rare], [Missile hit], [17], [30.8%], [18.1%], [+12.7],
  [Rare], [Enemy crash], [17], [41.3%], [18.1%], [+23.2],
  [Rare], [Wall crash], [16], [31.9%], [17.6%], [+14.3],
  [Win], [Missile hit], [14], [61.5%], [45.0%], [+16.5],
  [Win], [Enemy crash], [14], [69.8%], [45.0%], [+24.8],
  [Win], [Wall crash], [13], [59.9%], [45.2%], [+14.7],
)
