// Generated by analysis/results.py.
#table(columns: (1fr, .7fr, 1fr, 1.3fr),
  table.header([*Task*], [*Participants*], [*Balanced accuracy*], [*95% bootstrap interval*]),
  [Oddball], [17], [80.7%], [76.5–84.4%],
  [Gambling], [14], [65.1%], [59.8–70.9%],
)
