// Generated by analysis/results.py.
#table(columns: (.65fr, 1.15fr, .8fr, .9fr, 1fr, 1fr),
  table.header([*Label*], [*Game event*], [*N*], [*Event labels*], [*Gameplay controls*], [*Difference*]),
  [Rare], [Missile hit], [17], [27.1%], [17.3%], [+9.8%],
  [Rare], [Enemy crash], [17], [42.5%], [17.3%], [+25.2%],
  [Rare], [Wall crash], [16], [31.3%], [17.0%], [+14.3%],
  [Win], [Missile hit], [14], [60.0%], [48.6%], [+11.3%],
  [Win], [Enemy crash], [14], [67.8%], [48.6%], [+19.1%],
  [Win], [Wall crash], [13], [58.1%], [48.9%], [+9.2%],
)
