// Generated by scripts/make_report_eegnet_defaults.py.
#table(columns: (.65fr, 1.15fr, .8fr, .9fr, 1fr, 1fr),
  table.header([*Label*], [*Game event*], [*N*], [*Event labels*], [*Gameplay controls*], [*Difference (pp)*]),
  [Rare], [Missile hit], [17], [29.6%], [17.7%], [+11.9],
  [Rare], [Enemy crash], [17], [41.3%], [17.7%], [+23.6],
  [Rare], [Wall crash], [16], [31.7%], [17.2%], [+14.5],
  [Win], [Missile hit], [14], [65.1%], [48.3%], [+16.8],
  [Win], [Enemy crash], [14], [74.3%], [48.3%], [+26.0],
  [Win], [Wall crash], [13], [63.3%], [48.3%], [+15.1],
)
