// Generated by scripts/make_report_eegnet_defaults.py.
#table(columns: (1fr, .7fr, 1fr, 1.3fr),
  table.header([*Task*], [*Participants*], [*Balanced accuracy*], [*Descriptive 95% interval*]),
  [Oddball], [17], [80.5%], [76.3–84.3%],
  [Gambling], [14], [66.6%], [60.8–72.3%],
)
