// Generated by analysis/results.py.
#table(columns: (1fr, 1.2fr, 1fr, 1fr, 1fr),
  table.header([*Exemplary category*], [*Source balanced accuracy*], [*Hit labels*], [*Enemy-crash labels*], [*Wall-crash labels*]),
  [Rare], [80.9%], [20.6%], [26.6%], [21.1%],
  [Standard], [76.3%], [29.1%], [23.8%], [23.1%],
  [Win], [74.5%], [26.6%], [31.7%], [25.0%],
  [Loss], [73.7%], [19.2%], [17.8%], [18.3%],
)
